SELECT
    PK_PRODUCT,
    FK_PRODUCTSUBCATEGORYID,
    FK_PRODUCTMODELID,
    NAME_PRODUCT,
    COLOR,
    SIZES,
    NAME_SUBCATEGORY,
    NAME_CATEGORY
FROM {{ ref('int_snowflake__products') }}
