SELECT
    PK_SALESORDERDETAILID,
    fk_addressid,
    pk_salesorderid,
    FK_CUSTOMERID,
    FK_SALESPERSONID,
    FK_TERRITORYID,
    FK_CREDITCARDID,
    creditcard_display,
    OH_ORDERDATE,
    OH_STATUS_DESCRIPTION as OH_STATUS,
    FK_PRODUCTID,
    FK_SPECIALOFFERID,
    OD_ORDERQTY,
    OD_UNITPRICE,
    OD_UNITPRICEDISCOUNT,
    FREIGHT_PER_ITEM,
    TAX_PER_ITEM,
    ITEM_TOTAL,
    DISCOUNTED_ITEM_TOTAL,
    OH_TOTALDUE
FROM {{ ref('int_snowflake__ordered_items') }}
